// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrm1HegsYmiihjfgZGtSQL73YEbuf_99o',
    appId: '1:24080540423:web:808c47700fe7388daddba2',
    messagingSenderId: '24080540423',
    projectId: 'smart-tasks-8386',
    authDomain: 'smart-tasks-8386.firebaseapp.com',
    storageBucket: 'smart-tasks-8386.firebasestorage.app',
    measurementId: 'G-XMPP2B90FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEX8LwP8doKeF3_ou_A6fYz26p_r-PRmk',
    appId: '1:24080540423:android:26f0f41dc5d3ddc4addba2',
    messagingSenderId: '24080540423',
    projectId: 'smart-tasks-8386',
    storageBucket: 'smart-tasks-8386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFsClZcKVmFle1YDZs_qsgckVDGiJhYXk',
    appId: '1:24080540423:ios:ef7ac122c01c439eaddba2',
    messagingSenderId: '24080540423',
    projectId: 'smart-tasks-8386',
    storageBucket: 'smart-tasks-8386.firebasestorage.app',
    iosClientId:
        '24080540423-6itq3ld4nhdkaf96t49v3um4arve8bl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFsClZcKVmFle1YDZs_qsgckVDGiJhYXk',
    appId: '1:24080540423:ios:ef7ac122c01c439eaddba2',
    messagingSenderId: '24080540423',
    projectId: 'smart-tasks-8386',
    storageBucket: 'smart-tasks-8386.firebasestorage.app',
    iosClientId:
        '24080540423-6itq3ld4nhdkaf96t49v3um4arve8bl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrm1HegsYmiihjfgZGtSQL73YEbuf_99o',
    appId: '1:24080540423:web:657f57af8eabaaf5addba2',
    messagingSenderId: '24080540423',
    projectId: 'smart-tasks-8386',
    authDomain: 'smart-tasks-8386.firebaseapp.com',
    storageBucket: 'smart-tasks-8386.firebasestorage.app',
    measurementId: 'G-5MTRQ9N8MJ',
  );
}
